---
## A Arch linux test
- hosts: ansiubu
  user: vagrant
  sudo: True

  tasks:
   - name: show the hostname
     action: command hostname
  
  tasks:
   - name: show the Disk Space
     action: command df -kh
